data:
  subsets: ["train", "val"]
  batch_size: 128

optimizer:
  optimizer_name: "Adam"
  lr: 1E-4

lr_scheduler:
  lr_scheduler_name: "cosine_with_warmup_and_restarts"
  warmup_epochs: 10
  cycle_epochs: 50